  
name: Deploy image

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    shell: bash
    defaults:
      run: 
        working-directory: ./terraform

    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0 

    - name: Set env variables
      run: |
        touch terraform.tfvars
        printf "ecr_container_image_url=${{ secrets.AWS_ECR_CONTAINER_IMAGE_URL }}\n" > terraform.tfvars
        printf "ecs_container_name=${{ secrets.AWS_ECS_CONTAINER_NAME }}\n" >> terraform.tfvars
        

    - name: Terraform init
      id: init
      run: terraform init -backend-config='bucket=${{ secrets.BUCKET_TF_STATE}}' -backend-config='key=${{ secrets.TF_STATE_KEY }}' -backend-config='region=${{ secrets.AWS_REGION }}' -backend-config='dynamodb_table=${{ secrets.AWS_DYNAMODB_TABLE }}'

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
    
    - name: Terraform Apply
      run: terraform apply -input=false -replace=aws_ecs_task_definition.main

