  
name: Deploy image

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run: 
        working-directory: ./terraform

    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2
      
    - name: Update ECS Service
      run: |
        which aws
        aws ecs update-service --cluster app-cluster --service app-service --force-new-deployment --region eu-west-2